TI Drop #6 180528a

diff --git a/inst_tools b/inst_tools
--- a/inst_tools
+++ b/inst_tools
@@ -17,30 +17,53 @@
 # will be updated, serving as documentation of required versions
 #
 
+# TODO : Add MD5SUM check on downloads to detect broken downloads
+# TODO : Test for deleted xdctools
+# TODO : Verify on MAC
+
+CACHEPATH="${CACHEPATH:-"$(cd "$(dirname "$0")"; pwd -P)/installs"}"
+
 declare -r ARM_NONE_GCC="https://developer.arm.com/-/media/Files/downloads/gnu-rm/7-2017q4/gcc-arm-none-eabi-7-2017-q4-major"
 
 declare -r MSP432E4_SDK="http://software-dl.ti.com/simplelink/esd/simplelink_msp432e4_sdk/2.10.00.17/simplelink_msp432e4_sdk_2_10_00_17"
 declare -r MSP432P4_SDK="http://software-dl.ti.com/simplelink/esd/simplelink_msp432_sdk/2.10.00.14/simplelink_msp432p4_sdk_2_10_00_14"
 
-# Someday ... when these are directly downloadable
-# declare -r CC13X2_SDK="http://software-dl.ti.com/simplelink/esd/simplelink_cc13x2_sdk/2.10.00.48/simplelink_cc13x2_sdk_2_10_00_48"
-# declare -r CC32XX_SDK="http://software-dl.ti.com/simplelink/esd/simplelink_cc32xx_sdk/2.10.00.04/simplelink_cc32xx_sdk_2_10_00_04"
+# Someday ... when these are directly downloadable... for now, these need to be downloaded manually and placed in the "CACHEPATH"
+declare -r CC13X2_SDK="http://software-dl.ti.com/simplelink/esd/simplelink_cc13x2_sdk/2.10.00.48/simplelink_cc13x2_sdk_2_10_00_48"
+declare -r CC32XX_SDK="http://software-dl.ti.com/simplelink/esd/simplelink_cc32xx_sdk/2.10.00.04/simplelink_cc32xx_sdk_2_10_00_04"
 
-CACHEPATH="file://$(cd "$(dirname "$0")"; pwd -P)/installs"
-declare -r CC13X2_SDK="$CACHEPATH/simplelink_cc13x2_sdk_2_10_00_48"
-declare -r CC32XX_SDK="$CACHEPATH/simplelink_cc32xx_sdk_2_10_00_04"
-declare -r CC3120_SDK="$CACHEPATH/simplelink_sdk_wifi_plugin_1_55_00_42_roger"
+# This is an addon, provided separately as a tarball until it is part of an official sdk - this also should be placed in "CACHEPATH"
+declare -r CC3120_SDK="file://copyManuallyIntoInstallCacheDirectory/simplelink_sdk_wifi_plugin_1_55_00_42_rogerSdk210"
+
+# Global retval for fetch
+fetch_retval=""
 
 fetch()
 {
+    fetch_retval=""
 
-    if curl -O -# -L $1
+    package=$(basename $1)
+    echo Fetching $package
+
+    pushd $CACHEPATH > /dev/null
+
+    if test -f $package
     then
-        basename $1
+        echo $package found in cache at $CACHEPATH
+        fetch_retval=$CACHEPATH/$package
     else
-        echo "could not download $1" 1>&2
-        exit 4
+        echo $package not found in cache, downloading from $1 ...
+        if curl -O -# -L $1
+        then
+            fetch_retval=$CACHEPATH/$package
+        else
+            popd > /dev/null
+            echo "could not download $1" 1>&2
+            exit 4
+        fi
     fi
+
+    popd > /dev/null
 }
 
 get_install_gcc()
@@ -54,13 +77,13 @@ get_install_gcc()
 
     if $1
     then
-        tarball=$(fetch $ARM_NONE_GCC"-linux.tar.bz2")
+        fetch $ARM_NONE_GCC"-linux.tar.bz2"
     else
-        tarball=$(fetch $ARM_NONE_GCC"-mac.tar.bz2")
+        fetch $ARM_NONE_GCC"-mac.tar.bz2"
     fi
 
-    tar xf $tarball
-    rm $tarball
+    echo Unpacking $gcc GCC codegen tools
+    tar xf $fetch_retval
 }
 
 get_install_sdk()
@@ -74,23 +97,39 @@ get_install_sdk()
 
     if $2
     then
-        inst_bin=$(fetch $1".run")
-        if [ $? == 0 ]
-        then
-            chmod +x $inst_bin
-            ./$inst_bin --mode unattended --prefix $PWD
-            rm $inst_bin
-        fi
+        fetch $1".run"
+        inst_bin=$fetch_retval
+
+        echo Installing $sdk from $inst_bin ...
+        chmod +x $inst_bin
+        $inst_bin --mode unattended --prefix $PWD
     else
-        inst_bin=$(fetch $1".app.zip")
-        if [ $? == 0 ]
-        then
-            unzip -q $inst_bin
-	    # the --args is for the macOS open command
-            open ./${inst_bin%.zip} --args --mode unattended --prefix $PWD
-            rm -r $inst_bin ${inst_bin%.zip}
-        fi
+        fetch $1".app.zip"
+        inst_bin=$fetch_retval
+
+        echo Installing $sdk from $inst_bin ...
+	# unzip outputs to PWD
+        unzip -q $inst_bin
+        # the --args is for the macOS open command
+	installer=$(basename ${inst_bin%.zip})
+        open $installer --args --mode unattended --prefix $PWD
+	rm -rf ./$installer
     fi
+}
+
+get_install_sdk_addon()
+{
+    addon=$(basename $1)
+    if test -d $addon
+    then
+        echo $addon already installed
+        return
+    fi
+
+    fetch $1".tar.gz"
+    tarball=$fetch_retval
+    echo Unpacking $addon addon
+    tar xf $tarball
 }
 
 main()
@@ -111,6 +150,8 @@ main()
             ;;
     esac
 
+    mkdir -p $CACHEPATH
+
     mkdir -p $dst
     if ! cd $dst
     then
@@ -118,12 +159,16 @@ main()
         exit 2
     fi
 
+    echo "INFO :: Board $board"
+    echo "INFO :: Installer Cache at $CACHEPATH"
+    echo "INFO :: Installed Tools at $dst"
+
     get_install_gcc $is_linux
 
     case $board in
         MSP_EXP432E401Y_CC3120)
             get_install_sdk $MSP432E4_SDK $is_linux
-            get_install_sdk $CC3120_SDK $is_linux
+            get_install_sdk_addon $CC3120_SDK $is_linux
             ;;
         *CC32*)
             echo "you must manually download CC32XX SDK" 1>&2
